syntax = "proto3";

package rentalaccommodation;

service RentalAccommodationService {
  rpc AddProperty (AddPropertyRequest) returns (AddPropertyResponse);
  rpc CreateUsers (stream UserProfile) returns (CreateUsersResponse);
  rpc UpdateProperty (UpdatePropertyRequest) returns (UpdatePropertyResponse);
  rpc ListProperties (ListPropertiesRequest) returns (stream Property);
  rpc RemoveProperty(RemovePropertyRequest) returns (RemovePropertyResponse);
  rpc SearchProperty(SearchPropertyRequest) returns (SearchPropertyResponse);
  rpc BookProperty(BookPropertyRequest) returns (BookPropertyResponse);
  rpc ConfirmBooking(ConfirmBookingRequest) returns (ConfirmBookingResponse);
}

message AddPropertyRequest {
  string property_name = 1;
  string location = 2;
  string property_type = 3;
  double price_per_night = 4;
  string status = 5;
}

message AddPropertyResponse {
  string property_id = 1;
  string message = 2;
}

message UserProfile {
  string user_id = 1;
  string full_name = 2;
  string email = 3;
  string role = 4;
}

message CreateUsersResponse {
  int32 users_created = 1;
  string message = 2;
}

message UpdatePropertyRequest {
  string property_id = 1;
  string property_name = 2;
  string location = 3;
  string property_type = 4;
  double price_per_night = 5;
  string status = 6;
}

message UpdatePropertyResponse {
  bool updated = 1;
  string message = 2;
  Property property = 3;
}

message ListPropertiesRequest {
  string location = 1;
  string property_type = 2;
}

message Property {
  string property_id = 1;
  string property_name = 2;
  string location = 3;
  string property_type = 4;
  double price_per_night = 5;
  string status = 6;
}

message SearchPropertyRequest {
  string property_id = 1;
}

message SearchPropertyResponse {
  Property property = 1;
  bool found = 2;
  string status_mesg = 3;

}

message RemovePropertyRequest {
  string property_id = 1;
  string host_id = 2;
}

message RemovePropertyResponse {
  bool success = 1;
  string message = 2;
  repeated Property remaining_properties = 3;
}

message BookPropertyRequest {
  string property_id = 1;
  string guest_id = 2;
  string check_in = 3;   
  string check_out = 4;  
}

message BookPropertyResponse {
  bool success = 1;
  string message = 2;
  string booking_request_id = 3;
}

message ConfirmBookingRequest {
  string booking_request_id = 1;
}

message ConfirmBookingResponse {
  bool success = 1;
  string message = 2;
  string booking_id = 3;
  double total_cost = 4;
}